name: Python Package Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
          ref: main       # Replace with your branch

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip' # Enable caching for pip dependencies


      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .[dev]
          python -m pip install -e .[jax]
          pre-commit install

      - name: pre-commit
        run: pre-commit run --all-files --verbose --show-diff-on-failure
        continue-on-error: true  # Allow failure for this step

      - name: pytest
        run: pytest --cov='pywavelet' --cov-report term-missing

      - name: Upload Coverage to Coveralls
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          coverage xml
          pip install coveralls
          coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
